//! Daemon (background service) management for `rmdd`.
//!
//! Exposes `rmdd enable|start|stop|restart` and routes each to the platform's
//! init system — **systemd `--user`** on Linux, **launchd** (a per-user agent) on
//! macOS. Everything is per-user (no sudo), matching the installer's `~/.local/bin`
//! layout. The generated service just runs bare `rmdd`, which reads its config from
//! the encrypted settings store (`rmdd set …`) — so no token ever lands in a unit
//! file or plist.
//!
//! Commands:
//!   `rmdd enable`        install the service + enable autostart + start it
//!   `rmdd disable`       disable autostart (keeps the unit; `enable` re-enables)
//!   `rmdd status`        print status (autostart + running state)
//!   `rmdd start`         start it (no-op if already running)
//!   `rmdd stop`          stop it
//!   `rmdd restart`       restart it
//!   `rmdd log [-f]`      show the service log (`-f` to follow)

use anyhow::{Context, bail};

/// systemd unit base name (the unit file is `rmd-host.service`).
#[cfg(target_os = "linux")]
const NAME: &str = "rmd-host";
/// launchd agent label.
#[cfg(target_os = "macos")]
const LABEL: &str = "com.brainwires.rmd-host";

/// Dispatch `rmdd <enable|disable|status|start|stop|restart|log>`.
pub fn run_command(args: &[String]) -> anyhow::Result<()> {
    match args[0].as_str() {
        "enable" => imp::enable(true),
        "disable" => imp::enable(false),
        "status" => imp::status(),
        "start" => imp::start(),
        "stop" => imp::stop(),
        "restart" => imp::restart(),
        "log" => imp::log(args.iter().skip(1).any(|a| a == "-f" || a == "--follow")),
        other => bail!("unknown service command '{other}'"),
    }
}

/// The absolute path to this running `rmdd`, baked into the generated unit/plist so
/// the service launches exactly the binary the user enabled.
fn rmdd_path() -> anyhow::Result<std::path::PathBuf> {
    std::env::current_exe().context("resolve the rmdd binary path")
}

fn home() -> std::path::PathBuf {
    std::path::PathBuf::from(std::env::var("HOME").unwrap_or_default())
}

// ===========================================================================
// Linux — systemd --user
// ===========================================================================
#[cfg(target_os = "linux")]
mod imp {
    use super::*;
    use std::process::Command;

    fn unit_path() -> std::path::PathBuf {
        home()
            .join(".config/systemd/user")
            .join(format!("{NAME}.service"))
    }

    /// Run `systemctl --user <args>` and return the completed output.
    fn systemctl(args: &[&str]) -> anyhow::Result<std::process::Output> {
        Command::new("systemctl")
            .arg("--user")
            .args(args)
            .output()
            .context("run `systemctl --user` (is systemd available for this user?)")
    }

    fn write_unit() -> anyhow::Result<()> {
        let path = unit_path();
        std::fs::create_dir_all(path.parent().unwrap()).context("create systemd user dir")?;
        let exe = rmdd_path()?;

        // There are two deployment shapes, and they need different systemd wiring:
        //
        //  * Normal desktop (GNOME/Wayland, or X11 via a display manager). The
        //    daemon MUST start as part of graphical-session.target, because the
        //    compositor imports WAYLAND_DISPLAY / XDG_CURRENT_DESKTOP /
        //    XDG_SESSION_TYPE (and DISPLAY/XAUTHORITY) into the systemd *user*
        //    environment only as that target is reached. Starting at boot
        //    (default.target) races ahead of that import: the daemon inherits a
        //    stale env, fails to detect GNOME/Wayland, and falls back to the X11
        //    capture path — which then dies with "Authorization required" because
        //    it has no valid X cookie. Binding to graphical-session.target makes
        //    the daemon inherit the correct env on every login, and PartOf makes it
        //    restart cleanly if the session restarts. We detect this shape from an
        //    unset or ":0" DISPLAY (the display manager owns :0).
        //
        //  * Explicit X server (e.g. a headless `DISPLAY=:99` Xvfb the operator
        //    starts themselves). There is no display-manager session and no
        //    graphical-session.target, so bind to default.target + linger and pass
        //    the chosen DISPLAY through so the X11 backend can reach it.
        let display = std::env::var("DISPLAY").unwrap_or_default();
        let custom_x_server = !display.is_empty() && display != ":0";

        // `-` prefix: optional file. Holds RMD_KEY_PASSPHRASE for at-rest identity
        // encryption; the daemon prefers it from the env (see identity.rs), falling
        // back to reading the file directly for the CLI.
        let env_file = "EnvironmentFile=-%h/.config/rmd/key.env";

        let unit = if custom_x_server {
            format!(
                "# Generated by `rmdd enable` for an explicit X server (DISPLAY={display}).\n\
                 # Runs bare rmdd, which reads its config from the encrypted settings\n\
                 # store (`rmdd set …`). No graphical session is assumed, so it starts at\n\
                 # boot via default.target (pair with `loginctl enable-linger`).\n\
                 [Unit]\n\
                 Description=ReachMyDevice host agent (remote desktop)\n\
                 After=graphical-session.target\n\n\
                 [Service]\n\
                 Type=simple\n\
                 Environment=DISPLAY={display}\n\
                 {env_file}\n\
                 ExecStart={exe}\n\
                 Restart=always\n\
                 RestartSec=3\n\n\
                 [Install]\n\
                 WantedBy=default.target\n",
                exe = exe.display(),
            )
        } else {
            format!(
                "# Generated by `rmdd enable`. Runs bare rmdd, which reads its config\n\
                 # from the encrypted settings store (`rmdd set …`).\n\
                 #\n\
                 # Bound to graphical-session.target (NOT default.target) so the daemon\n\
                 # inherits the compositor's imported environment (WAYLAND_DISPLAY etc.).\n\
                 # Starting at boot would race ahead of that import and fall back to a\n\
                 # broken X11 capture path.\n\
                 [Unit]\n\
                 Description=ReachMyDevice host agent (remote desktop)\n\
                 After=graphical-session.target\n\
                 PartOf=graphical-session.target\n\n\
                 [Service]\n\
                 Type=simple\n\
                 {env_file}\n\
                 ExecStart={exe}\n\
                 Restart=always\n\
                 RestartSec=3\n\n\
                 [Install]\n\
                 WantedBy=graphical-session.target\n",
                exe = exe.display(),
            )
        };
        std::fs::write(&path, unit).with_context(|| format!("write {}", path.display()))?;
        Ok(())
    }

    /// Ensure the unit file exists (write it if missing) and systemd has re-read it.
    fn ensure_unit() -> anyhow::Result<()> {
        if !unit_path().exists() {
            write_unit()?;
            let _ = systemctl(&["daemon-reload"]);
        }
        Ok(())
    }

    fn run_ok(args: &[&str]) -> anyhow::Result<()> {
        let o = systemctl(args)?;
        if o.status.success() {
            println!("✓ systemctl --user {}", args.join(" "));
            Ok(())
        } else {
            bail!(
                "systemctl --user {} failed: {}",
                args.join(" "),
                String::from_utf8_lossy(&o.stderr).trim()
            );
        }
    }

    pub fn enable(on: bool) -> anyhow::Result<()> {
        if on {
            // On an upgrade/re-enable, disable FIRST (while the old unit is still on
            // disk) so any WantedBy symlink from the previous [Install] target is
            // removed. Otherwise switching targets (e.g. default.target →
            // graphical-session.target) leaves a stale default.target.wants link that
            // double-starts the daemon at boot with the wrong, pre-session env.
            if unit_path().exists() {
                let _ = systemctl(&["disable", NAME]);
            }
            write_unit()?;
            // enable-linger so the service starts at boot and survives logout
            // (essential on a headless server).
            if let Ok(user) = std::env::var("USER") {
                let _ = Command::new("loginctl")
                    .arg("enable-linger")
                    .arg(user)
                    .status();
            }
            let _ = systemctl(&["daemon-reload"]);
            run_ok(&["enable", "--now", NAME])?;
            println!("Enabled: {NAME} auto-starts at boot and is running now (systemd --user).");
            println!(
                "Note: until you `rmdd set rendezvous_url/token`, it starts but idles unconfigured."
            );
        } else {
            let _ = systemctl(&["disable", NAME]);
            println!("Disabled {NAME} autostart (unit kept — `rmdd enable` to re-enable).");
        }
        Ok(())
    }

    pub fn start() -> anyhow::Result<()> {
        ensure_unit()?;
        run_ok(&["start", NAME]) // idempotent: no-op if already running
    }

    pub fn stop() -> anyhow::Result<()> {
        run_ok(&["stop", NAME])
    }

    pub fn restart() -> anyhow::Result<()> {
        ensure_unit()?;
        run_ok(&["restart", NAME])
    }

    pub fn status() -> anyhow::Result<()> {
        let read = |args: &[&str], dflt: &str| -> String {
            systemctl(args)
                .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
                .ok()
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| dflt.to_string())
        };
        let installed = unit_path().exists();
        let enabled = if installed {
            read(&["is-enabled", NAME], "disabled")
        } else {
            "not installed".into()
        };
        let active = read(&["is-active", NAME], "inactive");
        println!("{NAME} (systemd --user):  autostart={enabled}  state={active}");
        Ok(())
    }

    pub fn log(follow: bool) -> anyhow::Result<()> {
        // The --user service logs to the user journal. Inherit stdio so it streams
        // straight to the terminal (and `-f` follows until Ctrl-C).
        let mut c = Command::new("journalctl");
        c.arg("--user").arg("-u").arg(NAME);
        if follow {
            c.arg("-f");
        } else {
            c.arg("--no-pager").arg("-n").arg("200");
        }
        c.status()
            .context("run journalctl (is systemd available?)")?;
        Ok(())
    }
}

// ===========================================================================
// macOS — launchd (per-user agent)
// ===========================================================================
#[cfg(target_os = "macos")]
mod imp {
    use super::*;
    use std::process::Command;

    fn plist_path() -> std::path::PathBuf {
        home()
            .join("Library/LaunchAgents")
            .join(format!("{LABEL}.plist"))
    }

    /// launchd domain target for the current user's GUI session: `gui/<uid>`.
    fn domain() -> String {
        let uid = Command::new("id")
            .arg("-u")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .unwrap_or_default();
        format!("gui/{uid}")
    }

    fn target() -> String {
        format!("{}/{LABEL}", domain())
    }

    fn launchctl(args: &[&str]) -> anyhow::Result<std::process::Output> {
        Command::new("launchctl")
            .args(args)
            .output()
            .context("run `launchctl`")
    }

    fn write_plist() -> anyhow::Result<()> {
        let path = plist_path();
        std::fs::create_dir_all(path.parent().unwrap()).context("create LaunchAgents dir")?;
        let exe = rmdd_path()?;
        let logdir = home().join(".local/state/rmd");
        let _ = std::fs::create_dir_all(&logdir);
        let log = logdir.join("rmd-host.log");
        let plist = format!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
             <!-- Generated by `rmdd enable`. Runs bare rmdd, which reads its config\n\
                  from the encrypted settings store (`rmdd set …`). -->\n\
             <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
             <plist version=\"1.0\">\n<dict>\n  \
               <key>Label</key><string>{LABEL}</string>\n  \
               <key>ProgramArguments</key><array><string>{exe}</string></array>\n  \
               <key>RunAtLoad</key><true/>\n  \
               <key>KeepAlive</key><true/>\n  \
               <key>ThrottleInterval</key><integer>10</integer>\n  \
               <key>StandardErrorPath</key><string>{log}</string>\n  \
               <key>StandardOutPath</key><string>{log}</string>\n\
             </dict>\n</plist>\n",
            exe = exe.display(),
            log = log.display(),
        );
        std::fs::write(&path, plist).with_context(|| format!("write {}", path.display()))?;
        Ok(())
    }

    fn ensure_plist() -> anyhow::Result<()> {
        if !plist_path().exists() {
            write_plist()?;
            let path = plist_path();
            let _ = launchctl(&["bootstrap", &domain(), &path.to_string_lossy()]);
        }
        Ok(())
    }

    pub fn enable(on: bool) -> anyhow::Result<()> {
        let path = plist_path();
        if on {
            write_plist()?;
            // Reload cleanly: bootout any prior instance, (re)enable, bootstrap, start.
            let _ = launchctl(&["bootout", &target()]);
            let _ = launchctl(&["enable", &target()]);
            let o = launchctl(&["bootstrap", &domain(), &path.to_string_lossy()])?;
            if !o.status.success() {
                bail!(
                    "launchctl bootstrap failed: {}",
                    String::from_utf8_lossy(&o.stderr).trim()
                );
            }
            let _ = launchctl(&["kickstart", &target()]);
            println!("Enabled: {LABEL} auto-starts at login and is running now (launchd).");
            println!(
                "Note: until you `rmdd set rendezvous_url/token`, it starts but idles unconfigured."
            );
            println!(
                "Grant Screen Recording + Accessibility to rmdd in System Settings › Privacy & Security."
            );
        } else {
            let _ = launchctl(&["bootout", &target()]);
            let _ = launchctl(&["disable", &target()]);
            println!("Disabled {LABEL} autostart (plist kept — `rmdd enable` to re-enable).");
        }
        Ok(())
    }

    pub fn start() -> anyhow::Result<()> {
        ensure_plist()?;
        // `stop` boots the service out of launchd (so KeepAlive can't respawn it),
        // which unloads it even though the plist file still exists — so `start`
        // must (re)bootstrap it, not just kickstart it. Bootstrap is a harmless
        // error when it's already loaded (ignored here), so this lets `start`
        // recover from a prior `stop` instead of failing "Could not find service".
        let path = plist_path();
        let _ = launchctl(&["bootstrap", &domain(), &path.to_string_lossy()]);
        // kickstart is a no-op if already running; -k would force a restart.
        let o = launchctl(&["kickstart", &target()])?;
        if o.status.success() {
            println!("✓ started {LABEL}");
            Ok(())
        } else {
            bail!(
                "launchctl kickstart failed: {}",
                String::from_utf8_lossy(&o.stderr).trim()
            );
        }
    }

    pub fn stop() -> anyhow::Result<()> {
        // bootout unloads it (KeepAlive would otherwise immediately respawn it).
        let _ = launchctl(&["bootout", &target()]);
        println!("✓ stopped {LABEL}");
        Ok(())
    }

    pub fn restart() -> anyhow::Result<()> {
        ensure_plist()?;
        let o = launchctl(&["kickstart", "-k", &target()])?;
        if o.status.success() {
            println!("✓ restarted {LABEL}");
            Ok(())
        } else {
            bail!(
                "launchctl kickstart -k failed: {}",
                String::from_utf8_lossy(&o.stderr).trim()
            );
        }
    }

    pub fn status() -> anyhow::Result<()> {
        let installed = plist_path().exists();
        let loaded = launchctl(&["list", LABEL])
            .map(|o| o.status.success())
            .unwrap_or(false);
        let autostart = if installed {
            "on (RunAtLoad)"
        } else {
            "not installed"
        };
        let state = if loaded { "running" } else { "stopped" };
        println!("{LABEL} (launchd):  autostart={autostart}  state={state}");
        Ok(())
    }

    pub fn log(follow: bool) -> anyhow::Result<()> {
        // launchd writes the agent's stdout/stderr to this file (see the plist).
        let log = home().join(".local/state/rmd/rmd-host.log");
        if !log.exists() {
            bail!(
                "no log yet at {} — has the service run? (`rmdd enable`)",
                log.display()
            );
        }
        let mut c = Command::new("tail");
        if follow {
            c.arg("-f");
        } else {
            c.arg("-n").arg("200");
        }
        c.arg(&log);
        c.status().context("run tail")?;
        Ok(())
    }
}

// ===========================================================================
// Other platforms — not yet supported
// ===========================================================================
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
mod imp {
    pub fn enable(_on: bool) -> anyhow::Result<()> {
        anyhow::bail!(
            "rmdd service management is only supported on Linux (systemd) and macOS (launchd)"
        )
    }
    pub fn start() -> anyhow::Result<()> {
        enable(true)
    }
    pub fn stop() -> anyhow::Result<()> {
        enable(true)
    }
    pub fn restart() -> anyhow::Result<()> {
        enable(true)
    }
    pub fn status() -> anyhow::Result<()> {
        enable(true)
    }
    pub fn log(_follow: bool) -> anyhow::Result<()> {
        enable(true)
    }
}
